# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "develop", "feature/**", "hotfix/**", "relase/**" ]
  pull_request:
    branches: [ "master", "develop", "feature/**", "hotfix/**", "relase/**"  ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        mongodb-version: ['6.0']
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: secret
          MONGO_INITDB_DATABASE: test
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
         - 27017:27017
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go VERSION ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install dependencies
      run: go mod download
    
    - name: Test
      run: go test -v ./...
      env:
        DATABASE_URL: mongodb://test:secret@mongo:27017/test
