# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "develop", "feature/**", "hotfix/**", "relase/**" ]
  pull_request:
    branches: [ "master", "develop", "feature/**", "hotfix/**", "relase/**"  ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19.x]
        mongodb-version: ['6.0']
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go VERSION ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Setup Mongo v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    
    - name: Install dependencies
      run: go mod download
    
    - name: Test
      run: go test -v ./...
      env:
        DATABASE_URL: mongodb://test:secret@$127.0.0.1:27017/test
   
